# Generated by Django 2.0.1 on 2018-01-29 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('write', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='input',
        ),
        migrations.DeleteModel(
            name='output',
        ),
    ]
